services:
  db:
    image: mysql:9.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: web_crawler_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      target: development
    container_name: go_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - DB_SOURCE=mysql_user:1234@tcp(mysql_db:3306)/web_crawler_db?parseTime=true
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: nextjs_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
      - /app/public
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
      - WATCHPACK_POLLING=true

volumes:
  mysql_data:
